language: go

branches:
  except:
    - /exp_.*/

git:
  depth: 1
  
cache:
  apt: true
  directories:
  - "$HOME/opt"

env:
  global:
    - WAF_VERSION=waf-2.0.18
        
install: true

jobs:
  include:
    - go: "1.13.x"
      env: USEMOD=1
      script: go test -v ./...
          
    - stage: cpp-test-waf
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
      before_install:
        - export PATH=$HOME/opt/waf-${WAF_VERSION}:$PATH
        - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
        - test -x waf-light || {
          cd "$HOME/opt" &&
          wget "https://gitlab.com/ita1024/waf/-/archive/${WAF_VERSION}/waf-${WAF_VERSION}.tar.gz" &&
          tar -zxf "waf-${WAF_VERSION}.tar.gz" &&
          cd "waf-${WAF_VERSION}" &&
          ./waf-light configure build &&
          cd $TRAVIS_BUILD_DIR; }
      script:
        - cd ${TRAVIS_BUILD_DIR}/cpp
        - waf-light configure test

    - stage: cpp-test-cmake
      language: cpp
      dist: bionic
      script:
        - cd ${TRAVIS_BUILD_DIR}/cpp
        - mkdir build_cmake && cd build_cmake
        - cmake ..
        - make
        - ./test/fileseq_test

    - stage: deploy
      script: skip
      if: tag =~ ^v\d+
      deploy:
        provider: script
        skip_cleanup: true
        script: curl -sL http://git.io/goreleaser | bash
        on:
          tags: true
          condition: $TRAVIS_OS_NAME = linux
          
    - stage: doxygen 
      language: cpp
      addons:
        apt:
          packages: 
            - doxygen 
            - doxygen-doc 
            - doxygen-latex 
            - doxygen-gui 
            - graphviz
      script: 
        - cd cpp/docs && doxygen && cd $TRAVIS_BUILD_DIR
      deploy:
        provider: pages
        project-name: libfileseq
        local-dir: cpp/docs/build
        skip_cleanup: true
        keep-history: true
        github-token: $GH_REPO_TOKEN
        on:
          branch: master
